// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUS-xtB3KbVQu4kX-b6kIvgv2mewzB_0',
    appId: '1:752893008003:web:6dbbdbe9130499b98de3b6',
    messagingSenderId: '752893008003',
    projectId: 'damiu-app-ad9f7',
    authDomain: 'damiu-app-ad9f7.firebaseapp.com',
    storageBucket: 'damiu-app-ad9f7.firebasestorage.app',
    measurementId: 'G-7D4CC4DJG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgb8WD_0aNEbjrQRtStHdtMxw7fHOFLDc',
    appId: '1:752893008003:android:4f704868fb5b6b9d8de3b6',
    messagingSenderId: '752893008003',
    projectId: 'damiu-app-ad9f7',
    storageBucket: 'damiu-app-ad9f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb_cljf3_GlmFQQazE7L3NGpBWF8AV7bE',
    appId: '1:752893008003:ios:991a22fe9224a8e28de3b6',
    messagingSenderId: '752893008003',
    projectId: 'damiu-app-ad9f7',
    storageBucket: 'damiu-app-ad9f7.firebasestorage.app',
    iosBundleId: 'com.aylaqua.damiu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb_cljf3_GlmFQQazE7L3NGpBWF8AV7bE',
    appId: '1:752893008003:ios:991a22fe9224a8e28de3b6',
    messagingSenderId: '752893008003',
    projectId: 'damiu-app-ad9f7',
    storageBucket: 'damiu-app-ad9f7.firebasestorage.app',
    iosBundleId: 'com.aylaqua.damiu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPUS-xtB3KbVQu4kX-b6kIvgv2mewzB_0',
    appId: '1:752893008003:web:e361fe8a76d78bcf8de3b6',
    messagingSenderId: '752893008003',
    projectId: 'damiu-app-ad9f7',
    authDomain: 'damiu-app-ad9f7.firebaseapp.com',
    storageBucket: 'damiu-app-ad9f7.firebasestorage.app',
    measurementId: 'G-G2DT3VQPTV',
  );
}
